[package]
name = "decentra-chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
dirs = "5.0"
pgp = "0.14"
rand = "0.8"
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
socket2 = "0.5"
thiserror = "1"
tokio = { version = "1.0", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
toml = "0.8"
uuid = { version = "1.8", features = ["v4"] }

[dev-dependencies]
tempfile = "3.10"
